os: linux
language: shell

services:
- docker

addons:
  apt:
    packages:
    - docker-ce

  matrix:
  - ARCH=amd64 GOARCH=amd64 GOARM=6 QQEMU_ARCH=x86_64 TAG=amd64
  - ARCH=armhf GOARCH=arm   GOARM=6 QEMU_ARCH=arm     TAG=arm
  - ARCH=arm64 GOARCH=arm64 GOARM=6 QEMU_ARCH=arm64   TAG=arm64

before_install:
- mkdir ~/.docker && echo '{ "experimental":"enabled" }' > ~/.docker/config.json
- curl -L https://goss.rocks/install | sudo sh
- sudo apt-get -y install qemu-user-static
- docker run --rm --privileged multiarch/qemu-user-static:register

stages:
- name: test
- name: push

script:
- docker build -t visibilityspots/cloudflared:$TAG --build-arg ARCH="$ARCH" --build-arg
  GOARCH="$GOARCH" --build-arg GOARM="$GOARM" ./
- dgoss run --name cloudflared -ti visibilityspots/cloudflared:$TAG
- echo "$DOCKER_PASSWORD" | docker login --username visibilityspots --password-stdin
- docker push visibilityspots/cloudflared:$TAG

jobs:
  include:
  - stage: push
    script:
    - echo "$DOCKER_PASSWORD" | docker login --username visibilityspots --password-stdin
    - docker pull visibilityspots/cloudflared:arm
    - docker pull visibilityspots/cloudflared:arm64
    - docker pull visibilityspots/cloudflared:amd64
    - docker manifest create --amend visibilityspots/cloudflared:latest visibilityspots/cloudflared:arm
      visibilityspots/cloudflared:arm64 visibilityspots/cloudflared:amd64
    - docker manifest annotate visibilityspots/cloudflared:latest visibilityspots/cloudflared:arm
      --os linux --arch arm
    - docker manifest annotate visibilityspots/cloudflared:latest visibilityspots/cloudflared:arm64
      --os linux --arch arm64
    - docker manifest annotate visibilityspots/cloudflared:latest visibilityspots/cloudflared:amd64
      --os linux --arch amd64
    - docker manifest push --purge visibilityspots/cloudflared:latest

env:
  global:
    secure: nTT0E7Og68rCyPWKKf/J4208z5R/GHqPKXq7d5/MlikabiFJSttO0Qz1sMGu8qSAg3s1QdZrzB0gyspdIqIDTCtVYjJCxNx33+Uvmll2qd4iD0zAvlIQC1aPu2oC38c4tmyc9YZmNHeqSRiAmOPGm4LAL0weh+4hRshm+u78mkxfT7wHRBwIp7INBHoYz7D67omnztEBkvosrj39Zv1Ph/fHafNle6xUVaUGjialjjnJEfTuvmu0XDGZCm28cjudTMlWGJXcygn7dmPdT9S8LRtOPy6No2Xjo3t8B4gRsgo3pSAYcWEBZI+kst5MjVqE9qtZ47KA0jIayBTV6Gz2eKXM+iyms6TVRrT5xN8axB5f6KuwfiZm3btRj9SXtMLIJ/WhqYN+AF0qDYG1FaPGFP9BUXaTS+BkNjfAuDVsgQwx1oEJoQS+oEA89k6FU7ZmgJRq+oZPrmvrW+taRhM6NY2vCwiwRttBDWFTJTB4SdJ8qVkHbF1o1/79Wzr5bTwvI+HbbPibxfGLF2eeuSoju+7EDGV5E4ZeW/4BpUb+f6I7QpvrW/On3iiMe270z/j2uDWQlLUldS89ngCwWEIS8gIOM6ADx8YcuMSTSCLIR55CNKXxQMy4H0HDLeN3Y7/y6sRxmXv5iI0ESwYrh71g+waIFyHJUXCBuuZ72X+usoY=
